### ISSUE TITLE
Add the api-test folder to the new repository

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/api-test#2]
## Summary
Over time, the project has become too large, and it is now more appropriate to separate it from the current repository, finesse-backend. By transferring the "api-test" folder to a new repository, we can better organize our resources and facilitate management and collaboration on this project. Additionally, we intend to test APIs from other projects besides Finesse in the future. Hence, it would be beneficial to establish a common ground for all API testing.

## Tasks

- [x] Copy the `api-test` folder from the finesse-backend repository.

## Acceptance Criteria:

* The "api-test" folder is successfully added to the new repository.
* All tools and resources within the "api-test" folder are intact and functional in the new repository.

**Comment by rngadam** [comment]
Also of note in the description is we will eventually use this tool with any of our other API backend we build.

**Comment by ibrahim-kabir** [comment]
> Also of note in the description is we will eventually use this tool with any of our other API backend we build.

Added this to the description
